package com.recoverai.domain;
public enum RecoveryStatus { DETECTED, ANALYZING, ACTION_PENDING, ACTION_APPROVED, ACTION_BLOCKED, ACTION_EXECUTED, WAITING_CUSTOMER, RECOVERED, ESCALATED, STOPPED, UNRECOVERABLE }
