import {useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const api=import.meta.env.VITE_API_BASE_URL??'http://localhost:8080/api';
type Case={id:string;caseReference:string;customerName:string;riskType:string;amountAtRisk:number;paymentMethod:string;status:string;diagnosis?:string;recoverabilityScore?:number;recommendedAction?:string;reasons?:string[];attemptCount:number;activePaymentLink:boolean;amountRecovered:number};
type Audit={id:string;eventType:string;message:string;createdAt:string}; type Summary={totalRevenueAtRisk:number;revenueRecovered:number;recoveryRate:number;recoveredCases:number}; type Evaluation={dataClassification:string;datasetSize:number;seed:number;totalAtRisk:number;totalAttempted:number;totalRecovered:number;recoveryRate:number;policyApproved:number;policyBlocked:number;byRiskType:Record<string,{atRisk:number;attempted:number;recovered:number}>};
const label=(s?:string)=>s?.replaceAll('_',' ')??'—'; const money=(p:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(p/100);
async function get<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(api+path,{headers:{'Content-Type':'application/json'},...init});if(!r.ok){const b=await r.json().catch(()=>null);throw new Error(b?.message??`Request failed (${r.status})`)}return r.json()}
function Metric({value,name,good}:{value:string;name:string;good?:boolean}){return <article className={'metric '+(good?'good':'')}><small>{name}</small><strong>{value}</strong></article>}
function App(){const [view,setView]=useState<'overview'|'cases'|'simulation'>('overview'),[cases,setCases]=useState<Case[]>([]),[summary,setSummary]=useState<Summary>(),[selected,setSelected]=useState(''),[audit,setAudit]=useState<Audit[]>([]),[evaluation,setEvaluation]=useState<Evaluation>(),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showCreate,setShowCreate]=useState(false),[paymentUrl,setPaymentUrl]=useState(''),[draft,setDraft]=useState({customerName:'',customerEmail:'',amount:'4999'});const active=useMemo(()=>cases.filter(c=>!['RECOVERED','STOPPED','ESCALATED'].includes(c.status)),[cases]);const current=cases.find(c=>c.id===selected);
 const load=async()=>{setError('');try{const [a,b]=await Promise.all([get<Case[]>('/recovery-cases'),get<Summary>('/dashboard/summary')]);setCases(a);setSummary(b);setSelected(x=>x||a[0]?.id||'')}catch(e){setError(e instanceof Error?e.message:'Backend unavailable')}};
 const loadAudit=async(id:string)=>{try{setAudit(await get<Audit[]>(`/recovery-cases/${id}/audit`))}catch{}};useEffect(()=>{load()},[]);useEffect(()=>{if(selected)loadAudit(selected)},[selected]);useEffect(()=>{if(!selected||current?.status!=='WAITING_CUSTOMER')return;const timer=window.setInterval(()=>{load();loadAudit(selected)},5000);return()=>window.clearInterval(timer)},[selected,current?.status]);
 const act=async(action:'analyze'|'execute'|'stop')=>{if(!current)return;setBusy(true);setError('');try{const result=await get<any>(`/recovery-cases/${current.id}/${action}`,{method:'POST'});if(result?.paymentLink?.shortUrl)setPaymentUrl(result.paymentLink.shortUrl);setMessage(action==='analyze'?'Recommendation created.':action==='execute'?'Recovery action accepted. Continue to Razorpay Test Mode to complete the customer payment.':'Recovery action updated.');await load();await loadAudit(current.id)}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}};
 const createLiveCase=async()=>{const amount=Math.round(Number(draft.amount)*100);if(!draft.customerName.trim()||!Number.isFinite(amount)||amount<=0){setError('Enter a customer name and a valid positive amount.');return}setBusy(true);setError('');try{const created=await get<Case>('/recovery-cases',{method:'POST',body:JSON.stringify({customerName:draft.customerName.trim(),customerEmail:draft.customerEmail.trim(),contactAllowed:true,riskType:'PAYMENT_FAILURE',amountAtRisk:amount,paymentMethod:'UPI',failureReason:'customer_requested_retry',transactionStatus:'FAILED',previousSuccessfulPayments:1,previousFailedPayments:0})});setSelected(created.id);setShowCreate(false);setView('cases');setMessage('Live recovery case created. Analyze it, then execute the policy-approved payment link.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not create recovery case')}finally{setBusy(false)}};
 const simulate=async()=>{setBusy(true);try{setEvaluation(await get<Evaluation>('/evaluation/run',{method:'POST',body:JSON.stringify({datasetSize:240,seed:42})}));setView('simulation')}catch(e){setError(e instanceof Error?e.message:'Simulation failed')}finally{setBusy(false)}};
 return <div className="shell"><aside><div className="brand">RECOVER<span>AI</span></div><p>NOVACART<br/><small>Revenue operations</small></p>{(['overview','cases','simulation'] as const).map(x=><button className={view===x?'active':''} onClick={()=>setView(x)} key={x}>{x==='overview'?'Overview':x==='cases'?'Recovery cases':'Simulation lab'}</button>)}<footer>SAFETY MODE<br/><b>Policy controlled</b></footer></aside><main><header><div><em>REVENUE RECOVERY CONTROL CENTER</em><h1>{label(view)}</h1><p>Bounded recovery actions with deterministic policy checks.</p></div><button className="secondary" onClick={load}>Refresh</button></header>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}
 {view==='overview'&&<><section className="live-card"><div><em>LIVE TEST MODE FLOW</em><h2>Create a recovery payment</h2><p>A human creates the recovery case here. Card details and OTP are collected only by Razorpay on its hosted payment page.</p></div><button onClick={()=>setShowCreate(!showCreate)}>{showCreate?'Close form':'Start live recovery'}</button></section>{showCreate&&<section className="create-form"><label>Customer name<input value={draft.customerName} onChange={e=>setDraft({...draft,customerName:e.target.value})} placeholder="Customer name"/></label><label>Email (optional)<input value={draft.customerEmail} onChange={e=>setDraft({...draft,customerEmail:e.target.value})} placeholder="customer@example.com"/></label><label>Recovery amount (INR)<input type="number" min="1" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><button onClick={createLiveCase} disabled={busy}>Create recovery case</button></section>}<section className="metrics"><Metric name="Revenue at risk" value={money(summary?.totalRevenueAtRisk??0)}/><Metric name="Revenue recovered" value={money(summary?.revenueRecovered??0)} good/><Metric name="Recovery rate" value={`${Math.round(summary?.recoveryRate??0)}%`}/><Metric name="Active cases" value={String(active.length)}/></section><section className="columns"><article className="card"><h2>Recovery queue</h2><Rows cases={cases.slice(0,4)} select={x=>{setSelected(x);setView('cases')}}/></article><article className="card"><h2>Safety guardrails</h2><ul><li>Captured payments stop recovery</li><li>Contact permission is enforced</li><li>Duplicate links are blocked</li><li>Webhook events are idempotent</li></ul><button onClick={simulate} disabled={busy}>Run 240-case simulation</button></article></section></>}
 {view==='cases'&&<section className="casegrid"><article className="card"><h2>Firestore recovery queue</h2><Rows cases={cases} selected={selected} select={setSelected}/></article>{current&&<article className="detail"><div className="headline"><div><em>{current.caseReference}</em><h2>{current.customerName}</h2><p>{label(current.riskType)} · {current.paymentMethod}</p></div><b className="badge">{label(current.status)}</b></div><div className="amount"><small>Revenue at risk</small><strong>{money(current.amountAtRisk)}</strong>{current.amountRecovered>0&&<b>{money(current.amountRecovered)} recovered</b>}</div><section className="facts"><div><small>Diagnosis</small><b>{label(current.diagnosis)}</b></div><div><small>Recoverability</small><b>{current.recoverabilityScore===undefined?'Analyze first':`${Math.round(current.recoverabilityScore*100)}%`}</b></div><div><small>Action</small><b>{label(current.recommendedAction)}</b></div><div><small>Attempts</small><b>{current.attemptCount} / 3</b></div></section><section className="why"><h3>Decision rationale</h3>{(current.reasons??['No analysis yet.']).map(x=><p key={x}>{x}</p>)}</section><section className="actions">{!current.recommendedAction?<button onClick={()=>act('analyze')} disabled={busy}>Analyze case</button>:<button onClick={()=>act('execute')} disabled={busy||current.status==='RECOVERED'}>Execute approved action</button>}<button className="secondary" onClick={()=>act('stop')} disabled={busy||current.status==='RECOVERED'}>Stop recovery</button></section>{paymentUrl&&current.status==='WAITING_CUSTOMER'&&<section className="pay-next"><b>Customer payment step</b><p>Open the secure Razorpay Test Mode page. RecoverAI never sees the card number or OTP.</p><a href={paymentUrl} target="_blank" rel="noreferrer">Continue to Razorpay payment</a></section>}<section className="timeline"><h3>Audit timeline</h3>{audit.map(a=><div key={a.id}><b>{label(a.eventType)}</b><p>{a.message}</p><small>{new Date(a.createdAt).toLocaleString('en-IN')}</small></div>)}</section></article>}</section>}
 {view==='simulation'&&<article className="card simulation"><h2>Synthetic evaluation</h2><p>Simulated values never call Razorpay and are not real merchant revenue.</p><button onClick={simulate} disabled={busy}>Run simulation</button>{evaluation&&<><mark>SIMULATED · {evaluation.datasetSize} cases · seed {evaluation.seed}</mark><section className="metrics"><Metric name="At risk" value={money(evaluation.totalAtRisk)}/><Metric name="Attempted" value={money(evaluation.totalAttempted)}/><Metric name="Recovered" value={money(evaluation.totalRecovered)} good/><Metric name="Recovery rate" value={`${Math.round(evaluation.recoveryRate*100)}%`}/></section><p><b>{evaluation.policyApproved} approved</b> · {evaluation.policyBlocked} blocked by policy</p><div className="breakdown">{Object.entries(evaluation.byRiskType).map(([type,v])=><div key={type}><span>{label(type)}</span><i><b style={{width:`${v.atRisk?Math.round(v.recovered/v.atRisk*100):0}%`}}/></i><small>{money(v.recovered)} simulated recovered</small></div>)}</div></>}</article>}
 </main></div>}
function Rows({cases,select,selected}:{cases:Case[];select:(id:string)=>void;selected?:string}){return <div className="rows">{cases.map(c=><button className={selected===c.id?'selected':''} onClick={()=>select(c.id)} key={c.id}><span><b>{c.caseReference}</b><small>{label(c.riskType)}</small></span><span><b>{money(c.amountAtRisk)}</b><small>{label(c.status)}</small></span></button>)}</div>};createRoot(document.getElementById('root')!).render(<App/>);
